image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - cp -r build/ public/
  artifacts:
    paths:
      - public
  only:
    - master