image: node:20 # 或者使用你需要的 Node.js 版本

stages:
  - build

build_job:
  stage: build
  
  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public
  only:
    # Trigger a new build and deploy only when there is a push to the
    # below branch(es)
    - master